### ISSUE TITLE
Expose tokenizer state (dealing with script data correctly)

### ISSUE THREAD

**Issue by not-my-profile** [untitaker/html5gum#11]
I think most people who use an HTML5 tokenizer will want `<script><b>test</b></script>` to be tokenized as
```
StartTag(StartTag { self_closing: false, name: "script", attributes: {} })
String("<b>test</b>")
EndTag(EndTag { name: "script" })
```

instead of

```
StartTag(StartTag { self_closing: false, name: "script", attributes: {} })
StartTag(StartTag { self_closing: false, name: "b", attributes: {} })
String("test")
EndTag(EndTag { name: "b" })
EndTag(EndTag { name: "script" })
```

Unless I am missing something that doesn't seem to be possible with the current API?

Sidenote: It would also be nice to have some convenience utility that automatically dealt with the state implications of `script`, `style`, `title`, `textarea`, `iframe` etc. For example [the html tokenizer of the Python standard library](https://docs.python.org/3/library/html.parser.html) automatically takes care of `script` and `style`.

**Comment by untitaker** [comment]
>I think most people who use an HTML5 tokenizer will want <script><b>test</b></script> to be tokenized as

I don't fully understand how the referenced section about HTML fragments applies here by the way, but I haven't read it in detail.

For as long as html5gum doesn't give you a real treebuilder (i'm considering adding one), I think just exposing the state enum makes sense.

**Comment by not-my-profile** [comment]
The `get_state` method of my PR is not spec compliant for two reasons:

* it doesn't handle `noscript` since that depends on a flag ... this could be fixed by adding a `scripting: bool` parameter
* following the spec by switching to the script data state for `<script>` results in the following

```
% printf '<script><b>test</b></script>'  |  cargo run --example=switch-state    
StartTag(StartTag { self_closing: false, name: "script", attributes: {} })
String("<b>test")
EndTag(EndTag { name: "b" })
EndTag(EndTag { name: "script" })
```

which obviously is strictly undesirable ... I am actually not quite sure why that happens. If we could figure out why that happens and fix it / provide a way to work around it we could make `get_state` spec compliant.

**Comment by untitaker** [comment]
>which obviously is strictly undesirable

do you know how other tokenizers behave and what states they pass through? the state machine in html5gum is hand-written and i can't find any similar tests in html5lib-tests so it's easily possible that I messed up

**Comment by not-my-profile** [comment]
Oh yeah you messed up one state transition. I added a commit to fix it to my PR #13.

I also renamed `StartTag::get_state` to the more descriptive `next_state` and updated it to be fully spec compliant :)

**Comment by untitaker** [comment]
I'm gonna fix this in https://github.com/untitaker/html5gum/pull/41

thanks @not-my-profile... I should've acted on this sooner. I thought it would be possible to implement a tree builder in html5gum in a reasonable timeframe and kept punting on this issue. I see that lol-html has a similar mapping in its own sourcecode where I suspect yours was also from.

I'm still a bit afraid that people are going to make uninformed choices here. There are some extra checks in lol-html's source code that I don't fully understand that appear to have security implications if such a parser were to be used in browser-grade applications. See this: https://github.com/cloudflare/lol-html/blob/f40a9f767c41caf07851548d7470649a6019548c/src/parser/tree_builder_simulator/ambiguity_guard.rs#L1

**Comment by not-my-profile** [comment]
Thank you as well! I really like the name of the [naive_next_state](https://docs.rs/html5gum/0.5.7/html5gum/fn.naive_next_state.html) function you introduced, it nicely highlights that this prolly isn't completely sound.

Perhaps the `switch_states` method of the `DefaultEmitter` should be called `naive_switch_states` as well?

**Comment by untitaker** [comment]
yes makes sense. I would be fine with a pr that just makes the breaking change
